"""Add uploaded_file and transcript_file columns

Revision ID: 506363ff31d1
Revises: 
Create Date: 2025-10-24 02:14:41.072717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506363ff31d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('uploaded_file', sa.LargeBinary(), nullable=True))
    op.add_column('transcriptions', sa.Column('transcript_file', sa.LargeBinary(), nullable=True))
    op.drop_column('transcriptions', 'transcript_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('transcript_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transcriptions', 'transcript_file')
    op.drop_column('transcriptions', 'uploaded_file')
    # ### end Alembic commands ###
